# Generated by Django 3.2.3 on 2021-05-19 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_actor_id', models.PositiveIntegerField()),
                ('api_director_id', models.PositiveIntegerField()),
                ('api_movie_id', models.PositiveIntegerField()),
                ('api_genre_id', models.PositiveIntegerField()),
                ('api_similar_id', models.PositiveIntegerField()),
                ('up', models.BooleanField()),
                ('title', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
