# Generated by Django 3.2.3 on 2021-05-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_watchlist_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'api_provider_id')},
        ),
        migrations.AlterUniqueTogether(
            name='thumb',
            unique_together={('user', 'api_movie_id')},
        ),
    ]
