# Generated by Django 3.2.3 on 2021-05-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210524_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumb',
            name='api_actor_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='thumb',
            name='api_director_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='thumb',
            name='api_genre_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='thumb',
            name='api_similar_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
